# Generated by Django 4.2.7 on 2023-12-17 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_question_answer_count_alter_question_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='dislike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_dislikes', to='app.like'),
        ),
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_likes', to='app.like'),
        ),
    ]
