# Generated by Django 4.2.7 on 2023-12-21 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_like_count_vote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='profile',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('profile', 'question', 'answer')},
        ),
    ]
