# Generated by Django 4.2.7 on 2023-12-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_answer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/default.png', upload_to='img/avatars'),
        ),
    ]
