# Generated by Django 4.2.7 on 2023-12-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('profile', 'vote_type', 'question', 'answer')},
        ),
    ]
